name: 'trial_nov'
version: '1.0.0'
config-version: 2

profile: 'nov_trial'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

packages:
  - package: dbt-labs/dbt_utils
    version: 0.9.5

models:
  trial_nov: 
    +materialized: view
