version: 2

sources:
  - name: raw
    description: Raw data available in analytics database.
    database: analytics
    schema: raw
    tables:
      - name: zip_to_cbg
        description: (Bay Area sample of) Lookup from zip code to census block group.
      - name: cbg_total_pop
        description: 2020 US Census data for estimate total population by census block group.