select
    COUNTRY,
	XLAT as lat,
	XLON as lon,
	AGG_DAY_PERIOD,
	AGG_TIME_PERIOD,
	GEOGRAPHY,
	ACTIVITY_INDEX_TOTAL,
	BOUNDS,
	DATA_VERSION,
	GEO_AGGREGATION,
	DAILY_AGGREGATION,
	HOURLY_AGGREGATION
from
    {{ source('raw', 'mvmt_smpl_v2')}}